package view;

import model.Ponto;
import model.Quadrante;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author larim
 */
public class App extends javax.swing.JFrame {
    /**
     * Creates new form Questao2Ui
     */
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        xTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        yTxt = new javax.swing.JTextField();
        btAvaliar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        eixoYCheck = new javax.swing.JCheckBox();
        eixoXCheck = new javax.swing.JCheckBox();
        segundoQuadCheck = new javax.swing.JCheckBox();
        primeiroQuadCheck = new javax.swing.JCheckBox();
        quartoQuadCheck = new javax.swing.JCheckBox();
        terceiroQuadCheck = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Eixo X:");

        xTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xTxtActionPerformed(evt);
            }
        });

        jLabel2.setText("Eixo Y:");

        yTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yTxtActionPerformed(evt);
            }
        });

        btAvaliar.setText("Avaliar");
        btAvaliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAvaliarActionPerformed(evt);
            }
        });

        jLabel3.setText("Posição:");

        eixoYCheck.setText("Incide sobre o Eixo Y");
        eixoYCheck.setEnabled(false);
        eixoYCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eixoYCheckActionPerformed(evt);
            }
        });

        eixoXCheck.setText("Incide sobre o Eixo X");
        eixoXCheck.setEnabled(false);
        eixoXCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eixoXCheckActionPerformed(evt);
            }
        });

        segundoQuadCheck.setText("No 2º Quadrante");
        segundoQuadCheck.setEnabled(false);
        segundoQuadCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                segundoQuadCheckActionPerformed(evt);
            }
        });

        primeiroQuadCheck.setText("No 1º Quadrante");
        primeiroQuadCheck.setEnabled(false);
        primeiroQuadCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeiroQuadCheckActionPerformed(evt);
            }
        });

        quartoQuadCheck.setText("No 4º Quadrante");
        quartoQuadCheck.setEnabled(false);
        quartoQuadCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quartoQuadCheckActionPerformed(evt);
            }
        });

        terceiroQuadCheck.setText("No 3º Quadrante");
        terceiroQuadCheck.setEnabled(false);
        terceiroQuadCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terceiroQuadCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(xTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAvaliar))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(terceiroQuadCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quartoQuadCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(primeiroQuadCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(segundoQuadCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eixoXCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eixoYCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(xTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(yTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btAvaliar)))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eixoXCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eixoYCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(primeiroQuadCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(segundoQuadCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(terceiroQuadCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quartoQuadCheck)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void xTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xTxtActionPerformed

    private void yTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yTxtActionPerformed

    private void eixoYCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eixoYCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eixoYCheckActionPerformed

    private void eixoXCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eixoXCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eixoXCheckActionPerformed

    private void segundoQuadCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_segundoQuadCheckActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_segundoQuadCheckActionPerformed

    private void primeiroQuadCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeiroQuadCheckActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_primeiroQuadCheckActionPerformed

    private void quartoQuadCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quartoQuadCheckActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_quartoQuadCheckActionPerformed

    private void terceiroQuadCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terceiroQuadCheckActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_terceiroQuadCheckActionPerformed

    private void btAvaliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAvaliarActionPerformed
        // TODO add your handling code here:
        int x = Integer.parseInt(xTxt.getText());
        int y = Integer.parseInt(yTxt.getText());
        
        Ponto meuPonto = new Ponto(x,y);
        eixoXCheck.setSelected(meuPonto.estaIncidindoSobreX());
        eixoYCheck.setSelected(meuPonto.estaIncidindoSobreY());
        primeiroQuadCheck.setSelected(meuPonto.identificarQuadrante() == Quadrante.PRIMEIRO);
        segundoQuadCheck.setSelected(meuPonto.identificarQuadrante() == Quadrante.SEGUNDO);
        terceiroQuadCheck.setSelected(meuPonto.identificarQuadrante() == Quadrante.TERCEIRO);
        quartoQuadCheck.setSelected(meuPonto.identificarQuadrante() == Quadrante.QUARTO);


        
    }//GEN-LAST:event_btAvaliarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAvaliar;
    private javax.swing.JCheckBox eixoXCheck;
    private javax.swing.JCheckBox eixoYCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JCheckBox primeiroQuadCheck;
    private javax.swing.JCheckBox quartoQuadCheck;
    private javax.swing.JCheckBox segundoQuadCheck;
    private javax.swing.JCheckBox terceiroQuadCheck;
    private javax.swing.JTextField xTxt;
    private javax.swing.JTextField yTxt;
    // End of variables declaration//GEN-END:variables
}
